/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'project-categories': ProjectCategory;
    projects: Project;
    blogs: Blog;
    products: Product;
    careers: Career;
    applications: Application;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Central media library. Upload images and files here to use them across Products, Projects, and Blogs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for accessibility and SEO. E.g. "Sliding window installation in Mumbai villa"
   */
  alt: string;
  /**
   * Optional caption shown below the image on blog posts and project pages.
   */
  caption?: string | null;
  /**
   * Organise this file in the media library.
   */
  folder?: ('general' | 'products' | 'projects' | 'blogs' | 'team') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categories for grouping projects (e.g. Residential, Commercial, Hospitality). Each project belongs to exactly one category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: string;
  /**
   * Displayed as a tag/pill on project cards and in the site navigation.
   */
  name: string;
  /**
   * URL-safe identifier — auto-generated from the name if left blank. Used in filter queries on the project listing page.
   */
  slug?: string | null;
  /**
   * Optional short description shown on the category filter page (future). Not currently rendered on the frontend.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Project showcases for the Yantra portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * Shown on the project card, hero, and browser tab. Maximum 150 characters.
   */
  title: string;
  /**
   * URL path for the project page, e.g. /project/crowne-plaza-ortakoy. Click "Auto-generate" to derive from title, or type manually.
   */
  slug: string;
  /**
   * Internal reference number shown in the project hero (e.g. "1003").
   */
  projectNumber: string;
  /**
   * City or region where the project was installed.
   */
  location: string;
  /**
   * The project category (e.g. Residential, Commercial). Used on the listing page to group projects into category carousels.
   */
  category: string | ProjectCategory;
  /**
   * When checked, this project appears in the Featured Projects section on the home page.
   */
  isFeatured?: boolean | null;
  /**
   * Full-width background image for the project hero section. Ideal size: 1920×1080px (landscape). Select from the Media library.
   */
  heroImage: string | Media;
  /**
   * Technical specs displayed in the specifications strip on the project page. Minimum 2 · Maximum 5 entries.
   */
  specifications: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  /**
   * Heading for the project story section (left-side text panel).
   */
  storyTitle: string;
  /**
   * Narrative text describing the project. Shown with a "Read More" expand if too long. Plain text only — no markdown.
   */
  storyDescription: string;
  /**
   * Sticky image shown alongside the story text on the right. Ideal size: 800×1000px (portrait). Select from the Media library.
   */
  storyImage: string | Media;
  /**
   * Select 2–10 images from the media library for the interactive gallery viewer. Images appear in the order selected.
   */
  gallery: (string | Media)[];
  /**
   * Link blog articles that feature, reference, or discuss this project.
   */
  relatedBlogs?: (string | Blog)[] | null;
  /**
   * Link products used in this project (e.g. windows, skylights). Displayed in a carousel below the project.
   */
  relatedProducts?: (string | Product)[] | null;
  /**
   * Manually link similar or related projects. Overrides the auto-generated similar-by-category carousel.
   */
  relatedProjects?: (string | Project)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles and architectural insights published on the Yantra website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  /**
   * Shown in the blog hero, card, and browser tab.
   */
  title: string;
  /**
   * URL identifier for the article (e.g. /blog/understanding-aluminium-windows).
   */
  slug: string;
  /**
   * Auto-set on creation. Adjust if scheduling or back-dating.
   */
  date: string;
  author: string;
  /**
   * When checked, this article appears in the Featured Articles section on the home page.
   */
  isFeatured?: boolean | null;
  /**
   * Wide landscape image shown in the blog hero and on listing cards. Ideal: 1200×628px. Select from the Media library.
   */
  coverImage: string | Media;
  /**
   * Rich text editor. Use the toolbar to add headings, lists, links, blockquotes, and media images from the Media library. Images are served via Cloudinary CDN.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  body_html?: string | null;
  /**
   * Link projects referenced in this article. Displayed in a carousel below the article.
   */
  relatedProjects?: (string | Project)[] | null;
  /**
   * Link related blog articles. Displayed in a "Related Articles" carousel.
   */
  relatedBlogs?: (string | Blog)[] | null;
  /**
   * Link products featured or discussed in this article. Displayed in a carousel below the article.
   */
  relatedProducts?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yantra product catalogue — windows, doors, skylights, and glazing systems.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Full product name shown in the H1, cards, and browser tab.
   */
  title: string;
  /**
   * URL path for the product page, e.g. /products/solaglide-sliding-windows. Click "Auto-generate" to derive from title.
   */
  slug: string;
  /**
   * Short subtitle shown below the product name on the detail page.
   */
  subtitle: string;
  /**
   * Product category for breadcrumb navigation (e.g. "Window System", "Door System").
   */
  category: string;
  /**
   * When checked, this product appears in the Products section on the home page.
   */
  isFeatured?: boolean | null;
  /**
   * Product gallery images. The first image is shown as the cover on listing cards. Add multiple for the detail-page image carousel.
   */
  images: {
    image: string | Media;
    /**
     * Alt text for accessibility. Leave blank to use the media library alt.
     */
    alt?: string | null;
    id?: string | null;
  }[];
  /**
   * Main product narrative paragraph shown below the subtitle on the detail page.
   */
  description: string;
  /**
   * Key-value specification rows shown in the "Technical Specifications" table.
   */
  specs: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  /**
   * Interactive configurator options displayed on the product detail page. Each option has a type (colour swatch / image card / text button) and a list of choices.
   */
  customizations?:
    | {
        title: string;
        /**
         * How choices are rendered in the configurator.
         */
        type: 'color' | 'image' | 'text';
        /**
         * Available choices for this option. For colour: value = hex/CSS colour (e.g. "#1a1a1a"). For image: value = image URL or path. For text: value = label (same as name).
         */
        choices: {
          name: string;
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Accordion sections shown in the "Support & Documentation" panel on the product page. E.g. Installation Guide, Warranty Information, Maintenance Tips.
   */
  support?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Projects that feature or use this product.
   */
  relatedProjects?: (string | Project)[] | null;
  /**
   * Blog posts that feature or discuss this product.
   */
  relatedBlogs?: (string | Blog)[] | null;
  /**
   * Other products to show in the "Similar Products" carousel.
   */
  relatedProducts?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Active job openings displayed on the public careers page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: string;
  /**
   * Displayed as the job title on the careers page.
   */
  role: string;
  /**
   * Department this role belongs to. Common values: Engineering, Design, Sales, Operations, Marketing.
   */
  field: string;
  /**
   * Work location. E.g. "Mumbai, Maharashtra" or "Remote".
   */
  location: string;
  /**
   * Detailed job description shown when the role is expanded on the careers page. Include responsibilities, requirements, and what success looks like.
   */
  description: string;
  /**
   * When unchecked, this role is hidden from the careers page without being deleted. Useful for pausing hiring without losing the listing.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Job applications submitted through the public careers form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  /**
   * Submitted by the applicant — do not edit.
   */
  fullName: string;
  /**
   * Submitted by the applicant — do not edit.
   */
  email: string;
  /**
   * Submitted by the applicant — do not edit.
   */
  phone: string;
  /**
   * Google Drive link to the applicant's resume/CV. Click to open.
   */
  resumeLink: string;
  /**
   * Optional cover letter submitted by the applicant.
   */
  coverNote?: string | null;
  /**
   * The career listing this application was submitted against.
   */
  career: string | Career;
  /**
   * Update this as you review the application.
   */
  status: 'new' | 'reviewed' | 'shortlisted' | 'rejected';
  /**
   * Private notes visible only to admins. Never shared with the applicant.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: string | ProjectCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'careers';
        value: string | Career;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  projectNumber?: T;
  location?: T;
  category?: T;
  isFeatured?: T;
  heroImage?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  storyTitle?: T;
  storyDescription?: T;
  storyImage?: T;
  gallery?: T;
  relatedBlogs?: T;
  relatedProducts?: T;
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  author?: T;
  isFeatured?: T;
  coverImage?: T;
  body?: T;
  body_html?: T;
  relatedProjects?: T;
  relatedBlogs?: T;
  relatedProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  category?: T;
  isFeatured?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  description?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  customizations?:
    | T
    | {
        title?: T;
        type?: T;
        choices?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  support?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  relatedProjects?: T;
  relatedBlogs?: T;
  relatedProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  role?: T;
  field?: T;
  location?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  resumeLink?: T;
  coverNote?: T;
  career?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}