/**
 * GET /api/preview
 * ─────────────────────────────────────────────────────────────────────────────
 * Next.js Draft Mode enabler for Payload CMS previews.
 *
 * Flow:
 *   1. Payload CMS calls this URL when an editor clicks "Preview" (generated
 *      by the admin.preview function in each collection).
 *   2. We validate the shared secret (PAYLOAD_PREVIEW_SECRET) to prevent
 *      anyone from enabling Draft Mode without CMS access.
 *   3. We enable Next.js Draft Mode (sets __prerender_bypass cookie).
 *   4. We redirect to the actual frontend page path.
 *
 * This bypasses ISR caching so the page fetches fresh data from Payload,
 * letting editors see exactly how the saved document will look.
 *
 * URL format (generated by collection admin.preview):
 *   /api/preview?secret=<PAYLOAD_PREVIEW_SECRET>&collection=projects&slug=my-project
 *
 * Security notes:
 * - Secret validated before Draft Mode is enabled
 * - Redirect uses validated collection/slug to prevent open redirect
 * - Only GET (CMS opens new tab)
 *
 * To exit preview: GET /api/preview/exit
 */

import { draftMode } from 'next/headers'
import { redirect } from 'next/navigation'

// Collection slug → frontend URL prefix
const COLLECTION_PATHS = {
  projects: '/project',
  products: '/products',
  blogs:    '/blog',
}

export async function GET(request) {
  const { searchParams } = new URL(request.url)
  const secret     = searchParams.get('secret')
  const collection = searchParams.get('collection')
  const slug       = searchParams.get('slug')

  // 1. Validate the shared secret
  const previewSecret = process.env.PAYLOAD_PREVIEW_SECRET
  if (!previewSecret) {
    return new Response('Preview secret not configured', { status: 500 })
  }
  if (secret !== previewSecret) {
    return new Response('Invalid preview token', { status: 401 })
  }

  // 2. Validate the collection is one we support
  const pathPrefix = COLLECTION_PATHS[collection]
  if (!pathPrefix) {
    return new Response(`Unknown collection: ${collection}`, { status: 400 })
  }

  // 3. Validate slug — only allow URL-safe slugs (defence against open redirect)
  if (!slug || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    return new Response('Invalid slug', { status: 400 })
  }

  // 4. Enable Next.js Draft Mode (sets __prerender_bypass cookie)
  const draft = await draftMode()
  draft.enable()

  // 5. Redirect to the actual frontend page — safe because we validated path above
  redirect(`${pathPrefix}/${slug}`)
}
